# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_road_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(857, 573)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 70, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 70, 111, 31))
        self.label_2.setObjectName("label_2")
        self.inputLineEdit = QtWidgets.QLineEdit(Dialog)
        self.inputLineEdit.setGeometry(QtCore.QRect(150, 200, 113, 22))
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.outputLineEdit = QtWidgets.QLineEdit(Dialog)
        self.outputLineEdit.setGeometry(QtCore.QRect(330, 200, 113, 22))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.inputButton = QtWidgets.QPushButton(Dialog)
        self.inputButton.setGeometry(QtCore.QRect(150, 290, 93, 28))
        self.inputButton.setObjectName("inputButton")
        self.outputButton = QtWidgets.QPushButton(Dialog)
        self.outputButton.setGeometry(QtCore.QRect(330, 290, 93, 28))
        self.outputButton.setObjectName("outputButton")
        self.runButton = QtWidgets.QPushButton(Dialog)
        self.runButton.setGeometry(QtCore.QRect(170, 400, 93, 28))
        self.runButton.setObjectName("runButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Input GEO tiff"))
        self.label_2.setText(_translate("Dialog", "Output Directory"))
        self.inputButton.setText(_translate("Dialog", "inputButton"))
        self.outputButton.setText(_translate("Dialog", "outputButton"))
        self.runButton.setText(_translate("Dialog", "Run Detection"))
